version: '3'

volumes:
  auth_postgres_volume:  
  auth-redis-data:  

services:
  pg_auth:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data      
  migrator-auth:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure      

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - auth-redis-data:/data    


