version: '3'

volumes:
  auth_postgres_volume:  

services:
  pg_auth:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - auth_postgres_volume:/var/lib/postgresql/data      


